image: maven:3.6.3-jdk-11

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn clean install

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - echo "Deploying your application..."
    # Add your deployment steps here
